### ISSUE TITLE
Notify Payment

### ISSUE THREAD

**Issue by jtalel** [PHOENIX-MEDIA/Magento2-BankPayment#2]
I have an early Magento1-BankPayment installation that has "Payment Notification" option, so once customer transfer the money they can fill a form and notify details of bank/transfer (attach file also), is this something you are workign on or the Magento2 option is not going to have this?

**Comment by PHOENIX-MEDIA** [comment]
Are you sure, that you are talking about our Bank payment module? The magento 1 version does not have this feature neither.
So, at the moment we have no plans for such a feature, but I will add it as a feature request for internal discussion.
