### ISSUE TITLE
& escaped to &amp; in bank account name

### ISSUE THREAD

**Issue by zolthan** [PHOENIX-MEDIA/Magento2-BankPayment#3]
The escaper of the config provider escapes too much entities. It is not possible to write an & in a company name for example.

https://github.com/PHOENIX-MEDIA/Magento2-BankPayment/blob/bee1d5aeefd238895a94085b1f67ee81f8a87837/Model/BankPaymentConfigProvider.php#L130

![bankpayment-escape-error](https://user-images.githubusercontent.com/3035434/38249085-c3dbe348-374a-11e8-8441-1cbe11f0bf10.png)

**Comment by PHOENIX-MEDIA** [comment]
Fixed. Thank your for reporting the issue!

**Comment by zolthan** [comment]
Will you also release a new version for composer inclusion?
